# Generated by Django 4.1 on 2022-08-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drug',
        ),
    ]
